/**
 * Machine-generated from IR_LawPrep_Schools_v2.md — do not hand-edit rows.
 *
 * Dedup: first table row wins for institutionType. Schools listed again under
 * Women's Colleges or PPE-only tables keep their primary section type unless
 * they appear only in PPE (then LAC-IRFocus).
 *
 * All seeds use city: null — fill via Cowork/research import or manually later.
 */

export type SeedSchool = {
  name: string;
  state: string;
  city: string | null;
  institutionType: string;
};

export const SEED_SCHOOLS: SeedSchool[] = [
  { name: "Agnes Scott College", state: "GA", city: null, institutionType: "WomensCollege" },
  { name: "Allegheny College", state: "PA", city: null, institutionType: "LAC-IRFocus" },
  { name: "American University", state: "DC", city: null, institutionType: "Research-IRFocus" },
  { name: "Amherst College", state: "MA", city: null, institutionType: "LAC-HighlySelective" },
  { name: "Austin College", state: "TX", city: null, institutionType: "LAC-IRFocus" },
  { name: "Barnard College", state: "NY", city: null, institutionType: "LAC-HighlySelective" },
  { name: "Bates College", state: "ME", city: null, institutionType: "LAC-HighlySelective" },
  { name: "Beloit College", state: "WI", city: null, institutionType: "LAC-IRFocus" },
  { name: "Boston College", state: "MA", city: null, institutionType: "Research-HighSelectivity" },
  { name: "Boston University", state: "MA", city: null, institutionType: "Research-IRFocus" },
  { name: "Bowdoin College", state: "ME", city: null, institutionType: "LAC-HighlySelective" },
  { name: "Brigham Young University", state: "UT", city: null, institutionType: "Research-IRFocus" },
  { name: "Brown University", state: "RI", city: null, institutionType: "Research-HighSelectivity" },
  { name: "Bryn Mawr College", state: "PA", city: null, institutionType: "WomensCollege" },
  { name: "Bucknell University", state: "PA", city: null, institutionType: "LAC-HighlySelective" },
  { name: "Carleton College", state: "MN", city: null, institutionType: "LAC-HighlySelective" },
  { name: "Carnegie Mellon University", state: "PA", city: null, institutionType: "Research-HighSelectivity" },
  { name: "Centre College", state: "KY", city: null, institutionType: "LAC-IRFocus" },
  { name: "Claremont McKenna College", state: "CA", city: null, institutionType: "LAC-HighlySelective" },
  { name: "Colby College", state: "ME", city: null, institutionType: "LAC-HighlySelective" },
  { name: "Colgate University", state: "NY", city: null, institutionType: "LAC-HighlySelective" },
  { name: "Colorado College", state: "CO", city: null, institutionType: "LAC-IRFocus" },
  { name: "Columbia University", state: "NY", city: null, institutionType: "Research-HighSelectivity" },
  { name: "Connecticut College", state: "CT", city: null, institutionType: "LAC-IRFocus" },
  { name: "Dartmouth College", state: "NH", city: null, institutionType: "Research-HighSelectivity" },
  { name: "Davidson College", state: "NC", city: null, institutionType: "LAC-HighlySelective" },
  { name: "DePauw University", state: "IN", city: null, institutionType: "LAC-IRFocus" },
  { name: "Dickinson College", state: "PA", city: null, institutionType: "LAC-HighlySelective" },
  { name: "Duke University", state: "NC", city: null, institutionType: "Research-HighSelectivity" },
  { name: "Earlham College", state: "IN", city: null, institutionType: "LAC-IRFocus" },
  { name: "Elon University", state: "NC", city: null, institutionType: "LAC-IRFocus" },
  { name: "Emory University", state: "GA", city: null, institutionType: "Research-HighSelectivity" },
  { name: "Flagler College", state: "FL", city: null, institutionType: "LAC-IRFocus" },
  { name: "Florida International University", state: "FL", city: null, institutionType: "Research-IRFocus" },
  { name: "Florida State University", state: "FL", city: null, institutionType: "Research-LargePublic" },
  { name: "Fordham University", state: "NY", city: null, institutionType: "Research-IRFocus" },
  { name: "Furman University", state: "SC", city: null, institutionType: "LAC-IRFocus" },
  { name: "George Mason University", state: "VA", city: null, institutionType: "Research-LargePublic" },
  { name: "George Washington University", state: "DC", city: null, institutionType: "Research-IRFocus" },
  { name: "Georgetown University", state: "DC", city: null, institutionType: "Research-HighSelectivity" },
  { name: "Gonzaga University", state: "WA", city: null, institutionType: "Research-IRFocus" },
  { name: "Grinnell College", state: "IA", city: null, institutionType: "LAC-HighlySelective" },
  { name: "Hamilton College", state: "NY", city: null, institutionType: "LAC-HighlySelective" },
  { name: "Hampden-Sydney College", state: "VA", city: null, institutionType: "LAC-IRFocus" },
  { name: "Harvard University", state: "MA", city: null, institutionType: "Research-HighSelectivity" },
  { name: "Haverford College", state: "PA", city: null, institutionType: "LAC-HighlySelective" },
  { name: "High Point University", state: "NC", city: null, institutionType: "LAC-IRFocus" },
  { name: "Hobart and William Smith Colleges", state: "NY", city: null, institutionType: "LAC-IRFocus" },
  { name: "Hollins University", state: "VA", city: null, institutionType: "WomensCollege" },
  { name: "Indiana University — Bloomington", state: "IN", city: null, institutionType: "Research-LargePublic" },
  { name: "James Madison University", state: "VA", city: null, institutionType: "Research-LargePublic" },
  { name: "Johns Hopkins University", state: "MD", city: null, institutionType: "Research-HighSelectivity" },
  { name: "Kalamazoo College", state: "MI", city: null, institutionType: "LAC-IRFocus" },
  { name: "Kenyon College", state: "OH", city: null, institutionType: "LAC-IRFocus" },
  { name: "King's College (PA)", state: "PA", city: null, institutionType: "LAC-IRFocus" },
  { name: "Lafayette College", state: "PA", city: null, institutionType: "LAC-HighlySelective" },
  { name: "Lawrence University", state: "WI", city: null, institutionType: "LAC-IRFocus" },
  { name: "Lewis & Clark College", state: "OR", city: null, institutionType: "LAC-IRFocus" },
  { name: "Loyola University Chicago", state: "IL", city: null, institutionType: "Research-IRFocus" },
  { name: "Macalester College", state: "MN", city: null, institutionType: "LAC-HighlySelective" },
  { name: "Marquette University", state: "WI", city: null, institutionType: "Research-IRFocus" },
  { name: "Michigan State University", state: "MI", city: null, institutionType: "Research-LargePublic" },
  { name: "Middlebury College", state: "VT", city: null, institutionType: "LAC-HighlySelective" },
  { name: "Mount Holyoke College", state: "MA", city: null, institutionType: "LAC-IRFocus" },
  { name: "Muhlenberg College", state: "PA", city: null, institutionType: "LAC-IRFocus" },
  { name: "New York University", state: "NY", city: null, institutionType: "Research-IRFocus" },
  { name: "Northeastern University", state: "MA", city: null, institutionType: "Research-IRFocus" },
  { name: "Northwestern University", state: "IL", city: null, institutionType: "Research-HighSelectivity" },
  { name: "Norwich University", state: "VT", city: null, institutionType: "LAC-IRFocus" },
  { name: "Notre Dame University", state: "IN", city: null, institutionType: "Research-HighSelectivity" },
  { name: "Oberlin College", state: "OH", city: null, institutionType: "LAC-HighlySelective" },
  { name: "Occidental College", state: "CA", city: null, institutionType: "LAC-IRFocus" },
  { name: "Ohio State University", state: "OH", city: null, institutionType: "Research-LargePublic" },
  { name: "Pennsylvania State University", state: "PA", city: null, institutionType: "Research-LargePublic" },
  { name: "Pepperdine University", state: "CA", city: null, institutionType: "Research-IRFocus" },
  { name: "Pitzer College", state: "CA", city: null, institutionType: "LAC-IRFocus" },
  { name: "Pomona College", state: "CA", city: null, institutionType: "LAC-HighlySelective" },
  { name: "Princeton University", state: "NJ", city: null, institutionType: "Research-HighSelectivity" },
  { name: "Purdue University", state: "IN", city: null, institutionType: "Research-LargePublic" },
  { name: "Rhodes College", state: "TN", city: null, institutionType: "LAC-IRFocus" },
  { name: "Rice University", state: "TX", city: null, institutionType: "Research-HighSelectivity" },
  { name: "Rollins College", state: "FL", city: null, institutionType: "LAC-IRFocus" },
  { name: "Saint Louis University", state: "MO", city: null, institutionType: "Research-IRFocus" },
  { name: "Scripps College", state: "CA", city: null, institutionType: "WomensCollege" },
  { name: "Seton Hall University", state: "NJ", city: null, institutionType: "Research-IRFocus" },
  { name: "Sewanee — University of the South", state: "TN", city: null, institutionType: "LAC-IRFocus" },
  { name: "Skidmore College", state: "NY", city: null, institutionType: "LAC-IRFocus" },
  { name: "Smith College", state: "MA", city: null, institutionType: "LAC-IRFocus" },
  { name: "St. Olaf College", state: "MN", city: null, institutionType: "LAC-IRFocus" },
  { name: "Stanford University", state: "CA", city: null, institutionType: "Research-HighSelectivity" },
  { name: "Swarthmore College", state: "PA", city: null, institutionType: "LAC-HighlySelective" },
  { name: "Sweet Briar College", state: "VA", city: null, institutionType: "WomensCollege" },
  { name: "Syracuse University", state: "NY", city: null, institutionType: "Research-IRFocus" },
  { name: "Texas A&M University", state: "TX", city: null, institutionType: "Research-LargePublic" },
  { name: "Texas Christian University", state: "TX", city: null, institutionType: "Research-IRFocus" },
  { name: "Trinity College", state: "CT", city: null, institutionType: "LAC-IRFocus" },
  { name: "Tufts University", state: "MA", city: null, institutionType: "Research-HighSelectivity" },
  { name: "Tulane University", state: "LA", city: null, institutionType: "Research-HighSelectivity" },
  { name: "University of Arizona", state: "AZ", city: null, institutionType: "Research-LargePublic" },
  { name: "University of California — Berkeley", state: "CA", city: null, institutionType: "Research-LargePublic" },
  { name: "University of California — Davis", state: "CA", city: null, institutionType: "Research-LargePublic" },
  { name: "University of California — Los Angeles", state: "CA", city: null, institutionType: "Research-LargePublic" },
  { name: "University of California — San Diego", state: "CA", city: null, institutionType: "Research-LargePublic" },
  { name: "University of Chicago", state: "IL", city: null, institutionType: "Research-HighSelectivity" },
  { name: "University of Colorado — Boulder", state: "CO", city: null, institutionType: "Research-LargePublic" },
  { name: "University of Delaware", state: "DE", city: null, institutionType: "Research-LargePublic" },
  { name: "University of Denver", state: "CO", city: null, institutionType: "Research-IRFocus" },
  { name: "University of Florida", state: "FL", city: null, institutionType: "Research-LargePublic" },
  { name: "University of Georgia", state: "GA", city: null, institutionType: "Research-LargePublic" },
  { name: "University of Illinois — Urbana-Champaign", state: "IL", city: null, institutionType: "Research-LargePublic" },
  { name: "University of Iowa", state: "IA", city: null, institutionType: "Research-LargePublic" },
  { name: "University of Kansas", state: "KS", city: null, institutionType: "Research-LargePublic" },
  { name: "University of Maryland — College Park", state: "MD", city: null, institutionType: "Research-LargePublic" },
  { name: "University of Miami", state: "FL", city: null, institutionType: "Research-IRFocus" },
  { name: "University of Michigan — Ann Arbor", state: "MI", city: null, institutionType: "Research-LargePublic" },
  { name: "University of Minnesota — Twin Cities", state: "MN", city: null, institutionType: "Research-LargePublic" },
  { name: "University of North Carolina — Chapel Hill", state: "NC", city: null, institutionType: "Research-LargePublic" },
  { name: "University of Pennsylvania", state: "PA", city: null, institutionType: "Research-HighSelectivity" },
  { name: "University of Pittsburgh", state: "PA", city: null, institutionType: "Research-LargePublic" },
  { name: "University of Puget Sound", state: "WA", city: null, institutionType: "LAC-IRFocus" },
  { name: "University of Richmond", state: "VA", city: null, institutionType: "Research-IRFocus" },
  { name: "University of Rochester", state: "NY", city: null, institutionType: "Research-HighSelectivity" },
  { name: "University of South Carolina", state: "SC", city: null, institutionType: "Research-LargePublic" },
  { name: "University of Southern California", state: "CA", city: null, institutionType: "Research-IRFocus" },
  { name: "University of Tennessee", state: "TN", city: null, institutionType: "Research-LargePublic" },
  { name: "University of Texas at Austin", state: "TX", city: null, institutionType: "Research-LargePublic" },
  { name: "University of the Pacific", state: "CA", city: null, institutionType: "LAC-IRFocus" },
  { name: "University of Virginia", state: "VA", city: null, institutionType: "Research-LargePublic" },
  { name: "University of Washington", state: "WA", city: null, institutionType: "Research-LargePublic" },
  { name: "University of Wisconsin — Madison", state: "WI", city: null, institutionType: "Research-LargePublic" },
  { name: "Vanderbilt University", state: "TN", city: null, institutionType: "Research-HighSelectivity" },
  { name: "Vassar College", state: "NY", city: null, institutionType: "LAC-HighlySelective" },
  { name: "Virginia Tech", state: "VA", city: null, institutionType: "Research-LargePublic" },
  { name: "Wake Forest University", state: "NC", city: null, institutionType: "Research-HighSelectivity" },
  { name: "Washington and Lee University", state: "VA", city: null, institutionType: "LAC-HighlySelective" },
  { name: "Washington University in St. Louis", state: "MO", city: null, institutionType: "Research-HighSelectivity" },
  { name: "Wellesley College", state: "MA", city: null, institutionType: "LAC-HighlySelective" },
  { name: "Wesleyan University", state: "CT", city: null, institutionType: "LAC-HighlySelective" },
  { name: "Wheaton College", state: "MA", city: null, institutionType: "LAC-IRFocus" },
  { name: "Willamette University", state: "OR", city: null, institutionType: "LAC-IRFocus" },
  { name: "William & Mary", state: "VA", city: null, institutionType: "Research-LargePublic" },
  { name: "Williams College", state: "MA", city: null, institutionType: "LAC-HighlySelective" },
  { name: "Wofford College", state: "SC", city: null, institutionType: "LAC-IRFocus" },
  { name: "Yale University", state: "CT", city: null, institutionType: "Research-HighSelectivity" },
];

export const SEED_SCHOOL_COUNT = 144;
